upload/Controllers/uploadController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace upload.Controllers
{
    public class uploadController : Controller
    {
        // GET: Upload
        public ActionResult Index()
        {
            return View();
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public void Upload()
        {
            foreach (string file in Request.Files)
            {
                var postedFile = Request.Files[file];
                postedFile.SaveAs(Server.MapPath("~/UploadedFiles/") + Path.GetFileName(postedFile.FileName));
            }
        }

        public ActionResult List()
        {
            var uploadedFiles = new List<UploadedFile>();

            var files = Directory.GetFiles(Server.MapPath("~/UploadedFiles"));

            foreach (var file in files)
            {
                var fileInfo = new FileInfo(file);

                var uploadedFile = new UploadedFile() { Name = Path.GetFileName(file) };
                uploadedFile.Size = fileInfo.Length;

                uploadedFile.Path = ("~/UploadedFiles/") + Path.GetFileName(file);
                uploadedFiles.Add(uploadedFile);
            }

            return View(uploadedFiles);
        }
        


    }

}

    

upload/Views/upload/Display.cshtml
@model upload.Models.UploadedFiles

@{
    ViewBag.Title = "Display";
    Layout = "~/Views/Shared/_GameLayout.cshtml";
}
<p>
    @Html.ActionLink("Create New","upload")
</p>

    <% foreach (var file in Model)
       { %>
<tr>
    <td>
                <%= file.Name %>
    </td>
    <td>
        <%= (file.Size/1000) %> KB
    </td>
    <td>
        <%= Html.Image("previewImage",file.Path,new { width=100, height=100}) %>
    </td>
</tr>
    <% } %>